language: ruby
addons:
  postgresql: 9.3
rvm:
- 2.1.5
before_script:
- export DISPLAY=:0.0
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
deploy:
  provider: heroku
  api_key: <%= ENV['HEROKU_SECRET'] %>
  app: park-fail
